### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by gcotelli** [ba-st/ApplicationStarter#23]
Maybe we can brainstorm a better name and propose a logo for the project?

I was thinking in something like Launchpad keeping our space related metaphor among the projects.

If we agree in a new name we must release first a new version, and (instead of transferring the project) archiving it under the current name and create a new one so the projects currently using it won't break. Then we just change the README with a clear reference to the new one.

Thoughts?

**Comment by serpi90** [comment]
https://en.wikipedia.org/wiki/Spacecraft_propulsion#Launch-assist_mechanisms

Skyhook sounds nice

**Comment by mtabacman** [comment]
https://en.wikipedia.org/wiki/Launch_pad
This is better, mostly because it is a well know concept, and part of the normal current procedure for launching space stuff.

**Comment by gcotelli** [comment]
Done https://github.com/ba-st/Launchpad
